### ISSUE TITLE
add a link to the youtube channel you're uploading the replays to

### ISSUE THREAD

**Issue by h3oCharles** [TheBicPen/osu-lazer-bot#3]

**Comment by TheBicPen** [comment]
Sorry, but I am no longer actively working on this project. If you want to submit a PR, I'd be happy to take a look but I don't have time to add new features myself.

**Comment by TheBicPen** [comment]
There is a link in the readme. Here's the same link: https://www.youtube.com/channel/UCWUoXuSht6uy-evWTxpKFcQ
